CREATE OR REPLACE TABLE GOV_V2.GOVERNO.DESPESAS_ORGAO (
    MES_ANO                    VARCHAR(7),
    ORGAO_SUPERIOR             VARCHAR(200),
    ORGAO_ENTIDADE_VINCULADA   VARCHAR(200),
    VALOR_EMPENHADO            NUMBER(38,2),
    VALOR_LIQUIDADO            NUMBER(38,2),
    VALOR_PAGO                 NUMBER(38,2),
    VALOR_RESTOS_PAGAR_PAGOS   NUMBER(38,2)
);
